-- Rollback SGT Propostas v2.0
-- REMOVE as 290 colunas adicionadas para persistência de custos

ALTER TABLE Propostas
DROP COLUMN IF EXISTS total_v2_adm,
DROP COLUMN IF EXISTS total_v2_fun,
DROP COLUMN IF EXISTS total_v2_est,
DROP COLUMN IF EXISTS total_v2_con,
DROP COLUMN IF EXISTS total_v2_loc,

-- ADM
DROP COLUMN IF EXISTS adm_1_id, DROP COLUMN IF EXISTS adm_1_qtd, DROP COLUMN IF EXISTS adm_1_valor, DROP COLUMN IF EXISTS adm_1_periodo, DROP COLUMN IF EXISTS adm_1_subtotal,
DROP COLUMN IF EXISTS adm_2_id, DROP COLUMN IF EXISTS adm_2_qtd, DROP COLUMN IF EXISTS adm_2_valor, DROP COLUMN IF EXISTS adm_2_periodo, DROP COLUMN IF EXISTS adm_2_subtotal,
DROP COLUMN IF EXISTS adm_3_id, DROP COLUMN IF EXISTS adm_3_qtd, DROP COLUMN IF EXISTS adm_3_valor, DROP COLUMN IF EXISTS adm_3_periodo, DROP COLUMN IF EXISTS adm_3_subtotal,
DROP COLUMN IF EXISTS adm_4_id, DROP COLUMN IF EXISTS adm_4_qtd, DROP COLUMN IF EXISTS adm_4_valor, DROP COLUMN IF EXISTS adm_4_periodo, DROP COLUMN IF EXISTS adm_4_subtotal,
DROP COLUMN IF EXISTS adm_5_id, DROP COLUMN IF EXISTS adm_5_qtd, DROP COLUMN IF EXISTS adm_5_valor, DROP COLUMN IF EXISTS adm_5_periodo, DROP COLUMN IF EXISTS adm_5_subtotal,

-- FUN
DROP COLUMN IF EXISTS fun_1_id, DROP COLUMN IF EXISTS fun_1_qtd, DROP COLUMN IF EXISTS fun_1_dias, DROP COLUMN IF EXISTS fun_1_valor, DROP COLUMN IF EXISTS fun_1_encargos, DROP COLUMN IF EXISTS fun_1_subtotal,
DROP COLUMN IF EXISTS fun_2_id, DROP COLUMN IF EXISTS fun_2_qtd, DROP COLUMN IF EXISTS fun_2_dias, DROP COLUMN IF EXISTS fun_2_valor, DROP COLUMN IF EXISTS fun_2_encargos, DROP COLUMN IF EXISTS fun_2_subtotal,
DROP COLUMN IF EXISTS fun_3_id, DROP COLUMN IF EXISTS fun_3_qtd, DROP COLUMN IF EXISTS fun_3_dias, DROP COLUMN IF EXISTS fun_3_valor, DROP COLUMN IF EXISTS fun_3_encargos, DROP COLUMN IF EXISTS fun_3_subtotal,
DROP COLUMN IF EXISTS fun_4_id, DROP COLUMN IF EXISTS fun_4_qtd, DROP COLUMN IF EXISTS fun_4_dias, DROP COLUMN IF EXISTS fun_4_valor, DROP COLUMN IF EXISTS fun_4_encargos, DROP COLUMN IF EXISTS fun_4_subtotal,
DROP COLUMN IF EXISTS fun_5_id, DROP COLUMN IF EXISTS fun_5_qtd, DROP COLUMN IF EXISTS fun_5_dias, DROP COLUMN IF EXISTS fun_5_valor, DROP COLUMN IF EXISTS fun_5_encargos, DROP COLUMN IF EXISTS fun_5_subtotal,
DROP COLUMN IF EXISTS fun_6_id, DROP COLUMN IF EXISTS fun_6_qtd, DROP COLUMN IF EXISTS fun_6_dias, DROP COLUMN IF EXISTS fun_6_valor, DROP COLUMN IF EXISTS fun_6_encargos, DROP COLUMN IF EXISTS fun_6_subtotal,
DROP COLUMN IF EXISTS fun_7_id, DROP COLUMN IF EXISTS fun_7_qtd, DROP COLUMN IF EXISTS fun_7_dias, DROP COLUMN IF EXISTS fun_7_valor, DROP COLUMN IF EXISTS fun_7_encargos, DROP COLUMN IF EXISTS fun_7_subtotal,
DROP COLUMN IF EXISTS fun_8_id, DROP COLUMN IF EXISTS fun_8_qtd, DROP COLUMN IF EXISTS fun_8_dias, DROP COLUMN IF EXISTS fun_8_valor, DROP COLUMN IF EXISTS fun_8_encargos, DROP COLUMN IF EXISTS fun_8_subtotal,
DROP COLUMN IF EXISTS fun_9_id, DROP COLUMN IF EXISTS fun_9_qtd, DROP COLUMN IF EXISTS fun_9_dias, DROP COLUMN IF EXISTS fun_9_valor, DROP COLUMN IF EXISTS fun_9_encargos, DROP COLUMN IF EXISTS fun_9_subtotal,
DROP COLUMN IF EXISTS fun_10_id, DROP COLUMN IF EXISTS fun_10_qtd, DROP COLUMN IF EXISTS fun_10_dias, DROP COLUMN IF EXISTS fun_10_valor, DROP COLUMN IF EXISTS fun_10_encargos, DROP COLUMN IF EXISTS fun_10_subtotal,

-- EST
DROP COLUMN IF EXISTS est_1_id, DROP COLUMN IF EXISTS est_1_qtd, DROP COLUMN IF EXISTS est_1_dias, DROP COLUMN IF EXISTS est_1_valor, DROP COLUMN IF EXISTS est_1_subtotal,
DROP COLUMN IF EXISTS est_2_id, DROP COLUMN IF EXISTS est_2_qtd, DROP COLUMN IF EXISTS est_2_dias, DROP COLUMN IF EXISTS est_2_valor, DROP COLUMN IF EXISTS est_2_subtotal,
DROP COLUMN IF EXISTS est_3_id, DROP COLUMN IF EXISTS est_3_qtd, DROP COLUMN IF EXISTS est_3_dias, DROP COLUMN IF EXISTS est_3_valor, DROP COLUMN IF EXISTS est_3_subtotal,
DROP COLUMN IF EXISTS est_4_id, DROP COLUMN IF EXISTS est_4_qtd, DROP COLUMN IF EXISTS est_4_dias, DROP COLUMN IF EXISTS est_4_valor, DROP COLUMN IF EXISTS est_4_subtotal,
DROP COLUMN IF EXISTS est_5_id, DROP COLUMN IF EXISTS est_5_qtd, DROP COLUMN IF EXISTS est_5_dias, DROP COLUMN IF EXISTS est_5_valor, DROP COLUMN IF EXISTS est_5_subtotal,

-- CON
DROP COLUMN IF EXISTS con_1_id, DROP COLUMN IF EXISTS con_1_qtd, DROP COLUMN IF EXISTS con_1_kml, DROP COLUMN IF EXISTS con_1_litro, DROP COLUMN IF EXISTS con_1_km, DROP COLUMN IF EXISTS con_1_subtotal,
DROP COLUMN IF EXISTS con_2_id, DROP COLUMN IF EXISTS con_2_qtd, DROP COLUMN IF EXISTS con_2_kml, DROP COLUMN IF EXISTS con_2_litro, DROP COLUMN IF EXISTS con_2_km, DROP COLUMN IF EXISTS con_2_subtotal,
DROP COLUMN IF EXISTS con_3_id, DROP COLUMN IF EXISTS con_3_qtd, DROP COLUMN IF EXISTS con_3_kml, DROP COLUMN IF EXISTS con_3_litro, DROP COLUMN IF EXISTS con_3_km, DROP COLUMN IF EXISTS con_3_subtotal,
DROP COLUMN IF EXISTS con_4_id, DROP COLUMN IF EXISTS con_4_qtd, DROP COLUMN IF EXISTS con_4_kml, DROP COLUMN IF EXISTS con_4_litro, DROP COLUMN IF EXISTS con_4_km, DROP COLUMN IF EXISTS con_4_subtotal,
DROP COLUMN IF EXISTS con_5_id, DROP COLUMN IF EXISTS con_5_qtd, DROP COLUMN IF EXISTS con_5_kml, DROP COLUMN IF EXISTS con_5_litro, DROP COLUMN IF EXISTS con_5_km, DROP COLUMN IF EXISTS con_5_subtotal,
DROP COLUMN IF EXISTS con_6_id, DROP COLUMN IF EXISTS con_6_qtd, DROP COLUMN IF EXISTS con_6_kml, DROP COLUMN IF EXISTS con_6_litro, DROP COLUMN IF EXISTS con_6_km, DROP COLUMN IF EXISTS con_6_subtotal,
DROP COLUMN IF EXISTS con_7_id, DROP COLUMN IF EXISTS con_7_qtd, DROP COLUMN IF EXISTS con_7_kml, DROP COLUMN IF EXISTS con_7_litro, DROP COLUMN IF EXISTS con_7_km, DROP COLUMN IF EXISTS con_7_subtotal,
DROP COLUMN IF EXISTS con_8_id, DROP COLUMN IF EXISTS con_8_qtd, DROP COLUMN IF EXISTS con_8_kml, DROP COLUMN IF EXISTS con_8_litro, DROP COLUMN IF EXISTS con_8_km, DROP COLUMN IF EXISTS con_8_subtotal,
DROP COLUMN IF EXISTS con_9_id, DROP COLUMN IF EXISTS con_9_qtd, DROP COLUMN IF EXISTS con_9_kml, DROP COLUMN IF EXISTS con_9_litro, DROP COLUMN IF EXISTS con_9_km, DROP COLUMN IF EXISTS con_9_subtotal,
DROP COLUMN IF EXISTS con_10_id, DROP COLUMN IF EXISTS con_10_qtd, DROP COLUMN IF EXISTS con_10_kml, DROP COLUMN IF EXISTS con_10_litro, DROP COLUMN IF EXISTS con_10_km, DROP COLUMN IF EXISTS con_10_subtotal,
DROP COLUMN IF EXISTS con_11_id, DROP COLUMN IF EXISTS con_11_qtd, DROP COLUMN IF EXISTS con_11_kml, DROP COLUMN IF EXISTS con_11_litro, DROP COLUMN IF EXISTS con_11_km, DROP COLUMN IF EXISTS con_11_subtotal,
DROP COLUMN IF EXISTS con_12_id, DROP COLUMN IF EXISTS con_12_qtd, DROP COLUMN IF EXISTS con_12_kml, DROP COLUMN IF EXISTS con_12_litro, DROP COLUMN IF EXISTS con_12_km, DROP COLUMN IF EXISTS con_12_subtotal,
DROP COLUMN IF EXISTS con_13_id, DROP COLUMN IF EXISTS con_13_qtd, DROP COLUMN IF EXISTS con_13_kml, DROP COLUMN IF EXISTS con_13_litro, DROP COLUMN IF EXISTS con_13_km, DROP COLUMN IF EXISTS con_13_subtotal,
DROP COLUMN IF EXISTS con_14_id, DROP COLUMN IF EXISTS con_14_qtd, DROP COLUMN IF EXISTS con_14_kml, DROP COLUMN IF EXISTS con_14_litro, DROP COLUMN IF EXISTS con_14_km, DROP COLUMN IF EXISTS con_14_subtotal,
DROP COLUMN IF EXISTS con_15_id, DROP COLUMN IF EXISTS con_15_qtd, DROP COLUMN IF EXISTS con_15_kml, DROP COLUMN IF EXISTS con_15_litro, DROP COLUMN IF EXISTS con_15_km, DROP COLUMN IF EXISTS con_15_subtotal,
DROP COLUMN IF EXISTS con_16_id, DROP COLUMN IF EXISTS con_16_qtd, DROP COLUMN IF EXISTS con_16_kml, DROP COLUMN IF EXISTS con_16_litro, DROP COLUMN IF EXISTS con_16_km, DROP COLUMN IF EXISTS con_16_subtotal,
DROP COLUMN IF EXISTS con_17_id, DROP COLUMN IF EXISTS con_17_qtd, DROP COLUMN IF EXISTS con_17_kml, DROP COLUMN IF EXISTS con_17_litro, DROP COLUMN IF EXISTS con_17_km, DROP COLUMN IF EXISTS con_17_subtotal,
DROP COLUMN IF EXISTS con_18_id, DROP COLUMN IF EXISTS con_18_qtd, DROP COLUMN IF EXISTS con_18_kml, DROP COLUMN IF EXISTS con_18_litro, DROP COLUMN IF EXISTS con_18_km, DROP COLUMN IF EXISTS con_18_subtotal,
DROP COLUMN IF EXISTS con_19_id, DROP COLUMN IF EXISTS con_19_qtd, DROP COLUMN IF EXISTS con_19_kml, DROP COLUMN IF EXISTS con_19_litro, DROP COLUMN IF EXISTS con_19_km, DROP COLUMN IF EXISTS con_19_subtotal,
DROP COLUMN IF EXISTS con_20_id, DROP COLUMN IF EXISTS con_20_qtd, DROP COLUMN IF EXISTS con_20_kml, DROP COLUMN IF EXISTS con_20_litro, DROP COLUMN IF EXISTS con_20_km, DROP COLUMN IF EXISTS con_20_subtotal,

-- LOC
DROP COLUMN IF EXISTS loc_1_id_tipo, DROP COLUMN IF EXISTS loc_1_id_marca, DROP COLUMN IF EXISTS loc_1_qtd, DROP COLUMN IF EXISTS loc_1_valor, DROP COLUMN IF EXISTS loc_1_dias, DROP COLUMN IF EXISTS loc_1_subtotal,
DROP COLUMN IF EXISTS loc_2_id_tipo, DROP COLUMN IF EXISTS loc_2_id_marca, DROP COLUMN IF EXISTS loc_2_qtd, DROP COLUMN IF EXISTS loc_2_valor, DROP COLUMN IF EXISTS loc_2_dias, DROP COLUMN IF EXISTS loc_2_subtotal,
DROP COLUMN IF EXISTS loc_3_id_tipo, DROP COLUMN IF EXISTS loc_3_id_marca, DROP COLUMN IF EXISTS loc_3_qtd, DROP COLUMN IF EXISTS loc_3_valor, DROP COLUMN IF EXISTS loc_3_dias, DROP COLUMN IF EXISTS loc_3_subtotal,
DROP COLUMN IF EXISTS loc_4_id_tipo, DROP COLUMN IF EXISTS loc_4_id_marca, DROP COLUMN IF EXISTS loc_4_qtd, DROP COLUMN IF EXISTS loc_4_valor, DROP COLUMN IF EXISTS loc_4_dias, DROP COLUMN IF EXISTS loc_4_subtotal,
DROP COLUMN IF EXISTS loc_5_id_tipo, DROP COLUMN IF EXISTS loc_5_id_marca, DROP COLUMN IF EXISTS loc_5_qtd, DROP COLUMN IF EXISTS loc_5_valor, DROP COLUMN IF EXISTS loc_5_dias, DROP COLUMN IF EXISTS loc_5_subtotal,
DROP COLUMN IF EXISTS loc_6_id_tipo, DROP COLUMN IF EXISTS loc_6_id_marca, DROP COLUMN IF EXISTS loc_6_qtd, DROP COLUMN IF EXISTS loc_6_valor, DROP COLUMN IF EXISTS loc_6_dias, DROP COLUMN IF EXISTS loc_6_subtotal,
DROP COLUMN IF EXISTS loc_7_id_tipo, DROP COLUMN IF EXISTS loc_7_id_marca, DROP COLUMN IF EXISTS loc_7_qtd, DROP COLUMN IF EXISTS loc_7_valor, DROP COLUMN IF EXISTS loc_7_dias, DROP COLUMN IF EXISTS loc_7_subtotal,
DROP COLUMN IF EXISTS loc_8_id_tipo, DROP COLUMN IF EXISTS loc_8_id_marca, DROP COLUMN IF EXISTS loc_8_qtd, DROP COLUMN IF EXISTS loc_8_valor, DROP COLUMN IF EXISTS loc_8_dias, DROP COLUMN IF EXISTS loc_8_subtotal,
DROP COLUMN IF EXISTS loc_9_id_tipo, DROP COLUMN IF EXISTS loc_9_id_marca, DROP COLUMN IF EXISTS loc_9_qtd, DROP COLUMN IF EXISTS loc_9_valor, DROP COLUMN IF EXISTS loc_9_dias, DROP COLUMN IF EXISTS loc_9_subtotal,
DROP COLUMN IF EXISTS loc_10_id_tipo, DROP COLUMN IF EXISTS loc_10_id_marca, DROP COLUMN IF EXISTS loc_10_qtd, DROP COLUMN IF EXISTS loc_10_valor, DROP COLUMN IF EXISTS loc_10_dias, DROP COLUMN IF EXISTS loc_10_subtotal;
