
CREATE TABLE IF NOT EXISTS `service_type_blocks` (
  `id` int(11) AUTO_INCREMENT PRIMARY KEY,
  `service_type_id` int(11) NOT NULL,
  `block_slug` varchar(50) NOT NULL,
  `block_title` varchar(100) NOT NULL,
  `category` enum('layout','presentation','technical','financial','legal') DEFAULT 'technical',
  `display_order` int(11) DEFAULT 0,
  `is_required` tinyint(1) DEFAULT 1,
  `default_content` longtext,
  `allowed_vars` json,
  `is_active` tinyint(1) DEFAULT 1
);

INSERT INTO `service_type_blocks` (`service_type_id`, `block_slug`, `block_title`, `category`, `display_order`, `is_required`, `default_content`, `allowed_vars`, `is_active`) VALUES
(11, 'cabecalho', 'Cabeçalho', 'layout', 0, 1, '<p>Conteúdo padrão para Cabeçalho</p>', '["Cidade", "DataExtenso", "numero_proposta"]', 1),
(11, 'apresentacao', 'Apresentação', 'presentation', 1, 1, '<p>Conteúdo padrão para Apresentação</p>', '["Empresa"]', 1),
(11, 'finalidade', 'Finalidade', 'presentation', 2, 1, '<p>Conteúdo padrão para Finalidade</p>', '["finalidade"]', 1),
(11, 'escopo', 'Escopo dos Serviços', 'technical', 3, 1, '<p>Conteúdo padrão para Escopo dos Serviços</p>', '["area_obra"]', 1),
(11, 'metodologia', 'Metodologia', 'technical', 4, 1, '<p>Conteúdo padrão para Metodologia</p>', '[]', 1),
(11, 'documentacao', 'Documentação Técnica', 'technical', 5, 1, '<p>Conteúdo padrão para Documentação Técnica</p>', '[]', 1),
(11, 'equipamentos', 'Equipamentos Utilizados', 'technical', 6, 1, '<p>Conteúdo padrão para Equipamentos Utilizados</p>', '["Estacao_Total", "GPS", "Veiculo"]', 1),
(11, 'cronograma', 'Cronograma de Execução', 'technical', 7, 1, '<p>Conteúdo padrão para Cronograma de Execução</p>', '["prazo_execucao", "dias_campo", "dias_escritorio"]', 1),
(11, 'investimento', 'Investimento', 'financial', 8, 1, NULL, '["ValorProposta", "ValorExtenso"]', 1),
(11, 'condicoes_pagamento', 'Condições de Pagamento', 'financial', 9, 1, NULL, '["mobilizacao_percentual", "mobilizacao_valor", "restante_percentual", "restante_valor"]', 1),
(11, 'dados_bancarios', 'Dados Bancários', 'financial', 10, 1, NULL, '["Banco", "Agencia", "Conta", "PIX"]', 1),
(11, 'consideracoes', 'Considerações Finais', 'legal', 11, 1, '<p>Conteúdo padrão para Considerações Finais</p>', '["Empresa"]', 1),
(11, 'rodape', 'Rodapé', 'layout', 99, 1, '<p>Conteúdo padrão para Rodapé</p>', '["Empresa", "CNPJ", "whatsapp"]', 1),
(12, 'cabecalho', 'Cabeçalho', 'layout', 0, 1, '<p>Conteúdo padrão para Cabeçalho</p>', '["Cidade", "DataExtenso", "numero_proposta"]', 1),
(12, 'apresentacao', 'Apresentação', 'presentation', 1, 1, '<p>Conteúdo padrão para Apresentação</p>', '["Empresa"]', 1),
(12, 'finalidade', 'Finalidade', 'presentation', 2, 1, '<p>Conteúdo padrão para Finalidade</p>', '["finalidade"]', 1),
(12, 'escopo', 'Escopo dos Serviços', 'technical', 3, 1, '<p>Conteúdo padrão para Escopo dos Serviços</p>', '["area_obra"]', 1),
(12, 'metodologia', 'Metodologia', 'technical', 4, 1, '<p>Conteúdo padrão para Metodologia</p>', '[]', 1),
(12, 'documentacao', 'Documentação Técnica', 'technical', 5, 1, '<p>Conteúdo padrão para Documentação Técnica</p>', '[]', 1),
(12, 'equipamentos', 'Equipamentos Utilizados', 'technical', 6, 1, '<p>Conteúdo padrão para Equipamentos Utilizados</p>', '["Estacao_Total", "GPS", "Veiculo"]', 1),
(12, 'cronograma', 'Cronograma de Execução', 'technical', 7, 1, '<p>Conteúdo padrão para Cronograma de Execução</p>', '["prazo_execucao", "dias_campo", "dias_escritorio"]', 1),
(12, 'investimento', 'Investimento', 'financial', 8, 1, NULL, '["ValorProposta", "ValorExtenso"]', 1),
(12, 'condicoes_pagamento', 'Condições de Pagamento', 'financial', 9, 1, NULL, '["mobilizacao_percentual", "mobilizacao_valor", "restante_percentual", "restante_valor"]', 1),
(12, 'dados_bancarios', 'Dados Bancários', 'financial', 10, 1, NULL, '["Banco", "Agencia", "Conta", "PIX"]', 1),
(12, 'consideracoes', 'Considerações Finais', 'legal', 11, 1, '<p>Conteúdo padrão para Considerações Finais</p>', '["Empresa"]', 1),
(12, 'rodape', 'Rodapé', 'layout', 99, 1, '<p>Conteúdo padrão para Rodapé</p>', '["Empresa", "CNPJ", "whatsapp"]', 1),
(13, 'cabecalho', 'Cabeçalho', 'layout', 0, 1, '<p>Conteúdo padrão para Cabeçalho</p>', '["Cidade", "DataExtenso", "numero_proposta"]', 1),
(13, 'apresentacao', 'Apresentação', 'presentation', 1, 1, '<p>Conteúdo padrão para Apresentação</p>', '["Empresa"]', 1),
(13, 'finalidade', 'Finalidade', 'presentation', 2, 1, '<p>Conteúdo padrão para Finalidade</p>', '["finalidade"]', 1),
(13, 'escopo', 'Escopo dos Serviços', 'technical', 3, 1, '<p>Conteúdo padrão para Escopo dos Serviços</p>', '["area_obra"]', 1),
(13, 'metodologia', 'Metodologia', 'technical', 4, 1, '<p>Conteúdo padrão para Metodologia</p>', '[]', 1),
(13, 'documentacao', 'Documentação Técnica', 'technical', 5, 1, '<p>Conteúdo padrão para Documentação Técnica</p>', '[]', 1),
(13, 'equipamentos', 'Equipamentos Utilizados', 'technical', 6, 1, '<p>Conteúdo padrão para Equipamentos Utilizados</p>', '["Estacao_Total", "GPS", "Veiculo"]', 1),
(13, 'cronograma', 'Cronograma de Execução', 'technical', 7, 1, '<p>Conteúdo padrão para Cronograma de Execução</p>', '["prazo_execucao", "dias_campo", "dias_escritorio"]', 1),
(13, 'investimento', 'Investimento', 'financial', 8, 1, NULL, '["ValorProposta", "ValorExtenso"]', 1),
(13, 'condicoes_pagamento', 'Condições de Pagamento', 'financial', 9, 1, NULL, '["mobilizacao_percentual", "mobilizacao_valor", "restante_percentual", "restante_valor"]', 1),
(13, 'dados_bancarios', 'Dados Bancários', 'financial', 10, 1, NULL, '["Banco", "Agencia", "Conta", "PIX"]', 1),
(13, 'consideracoes', 'Considerações Finais', 'legal', 11, 1, '<p>Conteúdo padrão para Considerações Finais</p>', '["Empresa"]', 1),
(13, 'rodape', 'Rodapé', 'layout', 99, 1, '<p>Conteúdo padrão para Rodapé</p>', '["Empresa", "CNPJ", "whatsapp"]', 1),
(14, 'cabecalho', 'Cabeçalho', 'layout', 0, 1, '<p>Conteúdo padrão para Cabeçalho</p>', '["Cidade", "DataExtenso", "numero_proposta"]', 1),
(14, 'apresentacao', 'Apresentação', 'presentation', 1, 1, '<p>Conteúdo padrão para Apresentação</p>', '["Empresa"]', 1),
(14, 'finalidade', 'Finalidade', 'presentation', 2, 1, '<p>Conteúdo padrão para Finalidade</p>', '["finalidade"]', 1),
(14, 'escopo', 'Escopo dos Serviços', 'technical', 3, 1, '<p>Conteúdo padrão para Escopo dos Serviços</p>', '["area_obra"]', 1),
(14, 'metodologia', 'Metodologia', 'technical', 4, 1, '<p>Conteúdo padrão para Metodologia</p>', '[]', 1),
(14, 'documentacao', 'Documentação Técnica', 'technical', 5, 1, '<p>Conteúdo padrão para Documentação Técnica</p>', '[]', 1),
(14, 'equipamentos', 'Equipamentos Utilizados', 'technical', 6, 1, '<p>Conteúdo padrão para Equipamentos Utilizados</p>', '["Estacao_Total", "GPS", "Veiculo"]', 1),
(14, 'cronograma', 'Cronograma de Execução', 'technical', 7, 1, '<p>Conteúdo padrão para Cronograma de Execução</p>', '["prazo_execucao", "dias_campo", "dias_escritorio"]', 1),
(14, 'investimento', 'Investimento', 'financial', 8, 1, NULL, '["ValorProposta", "ValorExtenso"]', 1),
(14, 'condicoes_pagamento', 'Condições de Pagamento', 'financial', 9, 1, NULL, '["mobilizacao_percentual", "mobilizacao_valor", "restante_percentual", "restante_valor"]', 1),
(14, 'dados_bancarios', 'Dados Bancários', 'financial', 10, 1, NULL, '["Banco", "Agencia", "Conta", "PIX"]', 1),
(14, 'consideracoes', 'Considerações Finais', 'legal', 11, 1, '<p>Conteúdo padrão para Considerações Finais</p>', '["Empresa"]', 1),
(14, 'rodape', 'Rodapé', 'layout', 99, 1, '<p>Conteúdo padrão para Rodapé</p>', '["Empresa", "CNPJ", "whatsapp"]', 1),
(15, 'cabecalho', 'Cabeçalho', 'layout', 0, 1, '<p>Conteúdo padrão para Cabeçalho</p>', '["Cidade", "DataExtenso", "numero_proposta"]', 1),
(15, 'apresentacao', 'Apresentação', 'presentation', 1, 1, '<p>Conteúdo padrão para Apresentação</p>', '["Empresa"]', 1),
(15, 'finalidade', 'Finalidade', 'presentation', 2, 1, '<p>Conteúdo padrão para Finalidade</p>', '["finalidade"]', 1),
(15, 'escopo', 'Escopo dos Serviços', 'technical', 3, 1, '<p>Conteúdo padrão para Escopo dos Serviços</p>', '["area_obra"]', 1),
(15, 'metodologia', 'Metodologia', 'technical', 4, 1, '<p>Conteúdo padrão para Metodologia</p>', '[]', 1),
(15, 'documentacao', 'Documentação Técnica', 'technical', 5, 1, '<p>Conteúdo padrão para Documentação Técnica</p>', '[]', 1),
(15, 'equipamentos', 'Equipamentos Utilizados', 'technical', 6, 1, '<p>Conteúdo padrão para Equipamentos Utilizados</p>', '["Estacao_Total", "GPS", "Veiculo"]', 1),
(15, 'cronograma', 'Cronograma de Execução', 'technical', 7, 1, '<p>Conteúdo padrão para Cronograma de Execução</p>', '["prazo_execucao", "dias_campo", "dias_escritorio"]', 1),
(15, 'investimento', 'Investimento', 'financial', 8, 1, NULL, '["ValorProposta", "ValorExtenso"]', 1),
(15, 'condicoes_pagamento', 'Condições de Pagamento', 'financial', 9, 1, NULL, '["mobilizacao_percentual", "mobilizacao_valor", "restante_percentual", "restante_valor"]', 1),
(15, 'dados_bancarios', 'Dados Bancários', 'financial', 10, 1, NULL, '["Banco", "Agencia", "Conta", "PIX"]', 1),
(15, 'consideracoes', 'Considerações Finais', 'legal', 11, 1, '<p>Conteúdo padrão para Considerações Finais</p>', '["Empresa"]', 1),
(15, 'rodape', 'Rodapé', 'layout', 99, 1, '<p>Conteúdo padrão para Rodapé</p>', '["Empresa", "CNPJ", "whatsapp"]', 1),
(16, 'cabecalho', 'Cabeçalho', 'layout', 0, 1, '<p>Conteúdo padrão para Cabeçalho</p>', '["Cidade", "DataExtenso", "numero_proposta"]', 1),
(16, 'apresentacao', 'Apresentação', 'presentation', 1, 1, '<p>Conteúdo padrão para Apresentação</p>', '["Empresa"]', 1),
(16, 'finalidade', 'Finalidade', 'presentation', 2, 1, '<p>Conteúdo padrão para Finalidade</p>', '["finalidade"]', 1),
(16, 'escopo', 'Escopo dos Serviços', 'technical', 3, 1, '<p>Conteúdo padrão para Escopo dos Serviços</p>', '["area_obra"]', 1),
(16, 'metodologia', 'Metodologia', 'technical', 4, 1, '<p>Conteúdo padrão para Metodologia</p>', '[]', 1),
(16, 'documentacao', 'Documentação Técnica', 'technical', 5, 1, '<p>Conteúdo padrão para Documentação Técnica</p>', '[]', 1),
(16, 'equipamentos', 'Equipamentos Utilizados', 'technical', 6, 1, '<p>Conteúdo padrão para Equipamentos Utilizados</p>', '["Estacao_Total", "GPS", "Veiculo"]', 1),
(16, 'cronograma', 'Cronograma de Execução', 'technical', 7, 1, '<p>Conteúdo padrão para Cronograma de Execução</p>', '["prazo_execucao", "dias_campo", "dias_escritorio"]', 1),
(16, 'investimento', 'Investimento', 'financial', 8, 1, NULL, '["ValorProposta", "ValorExtenso"]', 1),
(16, 'condicoes_pagamento', 'Condições de Pagamento', 'financial', 9, 1, NULL, '["mobilizacao_percentual", "mobilizacao_valor", "restante_percentual", "restante_valor"]', 1),
(16, 'dados_bancarios', 'Dados Bancários', 'financial', 10, 1, NULL, '["Banco", "Agencia", "Conta", "PIX"]', 1),
(16, 'consideracoes', 'Considerações Finais', 'legal', 11, 1, '<p>Conteúdo padrão para Considerações Finais</p>', '["Empresa"]', 1),
(16, 'rodape', 'Rodapé', 'layout', 99, 1, '<p>Conteúdo padrão para Rodapé</p>', '["Empresa", "CNPJ", "whatsapp"]', 1),
(17, 'cabecalho', 'Cabeçalho', 'layout', 0, 1, '<p>Conteúdo padrão para Cabeçalho</p>', '["Cidade", "DataExtenso", "numero_proposta"]', 1),
(17, 'apresentacao', 'Apresentação', 'presentation', 1, 1, '<p>Conteúdo padrão para Apresentação</p>', '["Empresa"]', 1),
(17, 'finalidade', 'Finalidade', 'presentation', 2, 1, '<p>Conteúdo padrão para Finalidade</p>', '["finalidade"]', 1),
(17, 'escopo', 'Escopo dos Serviços', 'technical', 3, 1, '<p>Conteúdo padrão para Escopo dos Serviços</p>', '["area_obra"]', 1),
(17, 'metodologia', 'Metodologia', 'technical', 4, 1, '<p>Conteúdo padrão para Metodologia</p>', '[]', 1),
(17, 'documentacao', 'Documentação Técnica', 'technical', 5, 1, '<p>Conteúdo padrão para Documentação Técnica</p>', '[]', 1),
(17, 'equipamentos', 'Equipamentos Utilizados', 'technical', 6, 1, '<p>Conteúdo padrão para Equipamentos Utilizados</p>', '["Estacao_Total", "GPS", "Veiculo"]', 1),
(17, 'cronograma', 'Cronograma de Execução', 'technical', 7, 1, '<p>Conteúdo padrão para Cronograma de Execução</p>', '["prazo_execucao", "dias_campo", "dias_escritorio"]', 1),
(17, 'investimento', 'Investimento', 'financial', 8, 1, NULL, '["ValorProposta", "ValorExtenso"]', 1),
(17, 'condicoes_pagamento', 'Condições de Pagamento', 'financial', 9, 1, NULL, '["mobilizacao_percentual", "mobilizacao_valor", "restante_percentual", "restante_valor"]', 1),
(17, 'dados_bancarios', 'Dados Bancários', 'financial', 10, 1, NULL, '["Banco", "Agencia", "Conta", "PIX"]', 1),
(17, 'consideracoes', 'Considerações Finais', 'legal', 11, 1, '<p>Conteúdo padrão para Considerações Finais</p>', '["Empresa"]', 1),
(17, 'rodape', 'Rodapé', 'layout', 99, 1, '<p>Conteúdo padrão para Rodapé</p>', '["Empresa", "CNPJ", "whatsapp"]', 1),
(18, 'cabecalho', 'Cabeçalho', 'layout', 0, 1, '<p>Conteúdo padrão para Cabeçalho</p>', '["Cidade", "DataExtenso", "numero_proposta"]', 1),
(18, 'apresentacao', 'Apresentação', 'presentation', 1, 1, '<p>Conteúdo padrão para Apresentação</p>', '["Empresa"]', 1),
(18, 'finalidade', 'Finalidade', 'presentation', 2, 1, '<p>Conteúdo padrão para Finalidade</p>', '["finalidade"]', 1),
(18, 'escopo', 'Escopo dos Serviços', 'technical', 3, 1, '<p>Conteúdo padrão para Escopo dos Serviços</p>', '["area_obra"]', 1),
(18, 'metodologia', 'Metodologia', 'technical', 4, 1, '<p>Conteúdo padrão para Metodologia</p>', '[]', 1),
(18, 'documentacao', 'Documentação Técnica', 'technical', 5, 1, '<p>Conteúdo padrão para Documentação Técnica</p>', '[]', 1),
(18, 'equipamentos', 'Equipamentos Utilizados', 'technical', 6, 1, '<p>Conteúdo padrão para Equipamentos Utilizados</p>', '["Estacao_Total", "GPS", "Veiculo"]', 1),
(18, 'cronograma', 'Cronograma de Execução', 'technical', 7, 1, '<p>Conteúdo padrão para Cronograma de Execução</p>', '["prazo_execucao", "dias_campo", "dias_escritorio"]', 1),
(18, 'investimento', 'Investimento', 'financial', 8, 1, NULL, '["ValorProposta", "ValorExtenso"]', 1),
(18, 'condicoes_pagamento', 'Condições de Pagamento', 'financial', 9, 1, NULL, '["mobilizacao_percentual", "mobilizacao_valor", "restante_percentual", "restante_valor"]', 1),
(18, 'dados_bancarios', 'Dados Bancários', 'financial', 10, 1, NULL, '["Banco", "Agencia", "Conta", "PIX"]', 1),
(18, 'consideracoes', 'Considerações Finais', 'legal', 11, 1, '<p>Conteúdo padrão para Considerações Finais</p>', '["Empresa"]', 1),
(18, 'rodape', 'Rodapé', 'layout', 99, 1, '<p>Conteúdo padrão para Rodapé</p>', '["Empresa", "CNPJ", "whatsapp"]', 1),
(19, 'cabecalho', 'Cabeçalho', 'layout', 0, 1, '<p>Conteúdo padrão para Cabeçalho</p>', '["Cidade", "DataExtenso", "numero_proposta"]', 1),
(19, 'apresentacao', 'Apresentação', 'presentation', 1, 1, '<p>Conteúdo padrão para Apresentação</p>', '["Empresa"]', 1),
(19, 'finalidade', 'Finalidade', 'presentation', 2, 1, '<p>Conteúdo padrão para Finalidade</p>', '["finalidade"]', 1),
(19, 'escopo', 'Escopo dos Serviços', 'technical', 3, 1, '<p>Conteúdo padrão para Escopo dos Serviços</p>', '["area_obra"]', 1),
(19, 'metodologia', 'Metodologia', 'technical', 4, 1, '<p>Conteúdo padrão para Metodologia</p>', '[]', 1),
(19, 'documentacao', 'Documentação Técnica', 'technical', 5, 1, '<p>Conteúdo padrão para Documentação Técnica</p>', '[]', 1),
(19, 'equipamentos', 'Equipamentos Utilizados', 'technical', 6, 1, '<p>Conteúdo padrão para Equipamentos Utilizados</p>', '["Estacao_Total", "GPS", "Veiculo", "Drone"]', 1),
(19, 'cronograma', 'Cronograma de Execução', 'technical', 7, 1, '<p>Conteúdo padrão para Cronograma de Execução</p>', '["prazo_execucao", "dias_campo", "dias_escritorio"]', 1),
(19, 'investimento', 'Investimento', 'financial', 8, 1, NULL, '["ValorProposta", "ValorExtenso"]', 1),
(19, 'condicoes_pagamento', 'Condições de Pagamento', 'financial', 9, 1, NULL, '["mobilizacao_percentual", "mobilizacao_valor", "restante_percentual", "restante_valor"]', 1),
(19, 'dados_bancarios', 'Dados Bancários', 'financial', 10, 1, NULL, '["Banco", "Agencia", "Conta", "PIX"]', 1),
(19, 'consideracoes', 'Considerações Finais', 'legal', 11, 1, '<p>Conteúdo padrão para Considerações Finais</p>', '["Empresa"]', 1),
(19, 'rodape', 'Rodapé', 'layout', 99, 1, '<p>Conteúdo padrão para Rodapé</p>', '["Empresa", "CNPJ", "whatsapp"]', 1),
(20, 'cabecalho', 'Cabeçalho', 'layout', 0, 1, '<p>Conteúdo padrão para Cabeçalho</p>', '["Cidade", "DataExtenso", "numero_proposta"]', 1),
(20, 'apresentacao', 'Apresentação', 'presentation', 1, 1, '<p>Conteúdo padrão para Apresentação</p>', '["Empresa"]', 1),
(20, 'finalidade', 'Finalidade', 'presentation', 2, 1, '<p>Conteúdo padrão para Finalidade</p>', '["finalidade"]', 1),
(20, 'escopo', 'Escopo dos Serviços', 'technical', 3, 1, '<p>Conteúdo padrão para Escopo dos Serviços</p>', '["area_obra"]', 1),
(20, 'metodologia', 'Metodologia', 'technical', 4, 1, '<p>Conteúdo padrão para Metodologia</p>', '[]', 1),
(20, 'documentacao', 'Documentação Técnica', 'technical', 5, 1, '<p>Conteúdo padrão para Documentação Técnica</p>', '[]', 1),
(20, 'equipamentos', 'Equipamentos Utilizados', 'technical', 6, 1, '<p>Conteúdo padrão para Equipamentos Utilizados</p>', '["Estacao_Total", "GPS", "Veiculo"]', 1),
(20, 'cronograma', 'Cronograma de Execução', 'technical', 7, 1, '<p>Conteúdo padrão para Cronograma de Execução</p>', '["prazo_execucao", "dias_campo", "dias_escritorio"]', 1),
(20, 'investimento', 'Investimento', 'financial', 8, 1, NULL, '["ValorProposta", "ValorExtenso"]', 1),
(20, 'condicoes_pagamento', 'Condições de Pagamento', 'financial', 9, 1, NULL, '["mobilizacao_percentual", "mobilizacao_valor", "restante_percentual", "restante_valor"]', 1),
(20, 'dados_bancarios', 'Dados Bancários', 'financial', 10, 1, NULL, '["Banco", "Agencia", "Conta", "PIX"]', 1),
(20, 'consideracoes', 'Considerações Finais', 'legal', 11, 1, '<p>Conteúdo padrão para Considerações Finais</p>', '["Empresa"]', 1),
(20, 'rodape', 'Rodapé', 'layout', 99, 1, '<p>Conteúdo padrão para Rodapé</p>', '["Empresa", "CNPJ", "whatsapp"]', 1),
(21, 'cabecalho', 'Cabeçalho', 'layout', 0, 1, '<p>Conteúdo padrão para Cabeçalho</p>', '["Cidade", "DataExtenso", "numero_proposta"]', 1),
(21, 'apresentacao', 'Apresentação', 'presentation', 1, 1, '<p>Conteúdo padrão para Apresentação</p>', '["Empresa"]', 1),
(21, 'finalidade', 'Finalidade', 'presentation', 2, 1, '<p>Conteúdo padrão para Finalidade</p>', '["finalidade"]', 1),
(21, 'escopo', 'Escopo dos Serviços', 'technical', 3, 1, '<p>Conteúdo padrão para Escopo dos Serviços</p>', '["area_obra"]', 1),
(21, 'metodologia', 'Metodologia', 'technical', 4, 1, '<p>Conteúdo padrão para Metodologia</p>', '[]', 1),
(21, 'documentacao', 'Documentação Técnica', 'technical', 5, 1, '<p>Conteúdo padrão para Documentação Técnica</p>', '[]', 1),
(21, 'equipamentos', 'Equipamentos Utilizados', 'technical', 6, 1, '<p>Conteúdo padrão para Equipamentos Utilizados</p>', '["Estacao_Total", "GPS", "Veiculo"]', 1),
(21, 'cronograma', 'Cronograma de Execução', 'technical', 7, 1, '<p>Conteúdo padrão para Cronograma de Execução</p>', '["prazo_execucao", "dias_campo", "dias_escritorio"]', 1),
(21, 'investimento', 'Investimento', 'financial', 8, 1, NULL, '["ValorProposta", "ValorExtenso"]', 1),
(21, 'condicoes_pagamento', 'Condições de Pagamento', 'financial', 9, 1, NULL, '["mobilizacao_percentual", "mobilizacao_valor", "restante_percentual", "restante_valor"]', 1),
(21, 'dados_bancarios', 'Dados Bancários', 'financial', 10, 1, NULL, '["Banco", "Agencia", "Conta", "PIX"]', 1),
(21, 'consideracoes', 'Considerações Finais', 'legal', 11, 1, '<p>Conteúdo padrão para Considerações Finais</p>', '["Empresa"]', 1),
(21, 'rodape', 'Rodapé', 'layout', 99, 1, '<p>Conteúdo padrão para Rodapé</p>', '["Empresa", "CNPJ", "whatsapp"]', 1);